// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sla.manager.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sla.manager.domain.EventDataOnDemand;

privileged aspect EventDataOnDemand_Roo_Configurable {
    
    declare @type: EventDataOnDemand: @Configurable;
    
}
